# Generated by Django 5.1.4 on 2025-01-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movieinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("year", models.IntegerField(null=True)),
                ("summary", models.TextField()),
                ("img", models.ImageField(upload_to="Movieinfo")),
            ],
        ),
    ]
